# SPDX-FileCopyrightText: 2025 Howetuft
#
#
# SPDX-License-Identifier: Apache-2.0


# Monitor buildability.
#
# This workflow periodically triggers a build of LuxCoreDeps to ensure it stays
# buildable. The build is typically launched on a daily basis.


name: LuxCore Dependency Monitoring

permissions:
  actions: read
  attestations: read
  checks: read
  deployments: read
  discussions: read
  issues: read
  models: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read
  security-events: read
  id-token: read

on:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  call-build-deps:
    uses: ./.github/workflows/build.yml
    with:
      luxdeps-version: "Monitor"
